version: 1
loggers:
  eval:
    level: DEBUG
    handlers: [console, fileEval]
  convert:
    level: DEBUG
    handlers: [console, fileConvert]
  train:
    level: DEBUG
    handlers: [console, fileTrain]
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: console
  fileEval:
    class: logging.FileHandler
    filename: logs/eval.log
    formatter: file
  fileConvert:
    class: logging.FileHandler
    filename: logs/convert.log
    formatter: file
  fileTrain:
    class: logging.FileHandler
    filename: logs/train.log
    formatter: file
formatters:
  console:
    '()': 'colorlog.ColoredFormatter'
    format: "{log_color}{asctime} [{levelname:.4}] {message}"
    style: "{"
  file:
    format: "{asctime} [{levelname:.4}] {message}"
    style: "{"