/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Server_CONSTANTS_H
#define Server_CONSTANTS_H

#include "Server_types.h"



class ServerConstants {
 public:
  ServerConstants();

};

extern const ServerConstants g_Server_constants;



#endif
