# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  pod 'SwiftyBeaver', '2.1.1'
end
