// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

class ProgressRequest {
  ProgressRequest({
    this.progress,
    this.hasError,
  });

  int? progress;

  bool? hasError;

  Object encode() {
    return <Object?>[
      progress,
      hasError,
    ];
  }

  static ProgressRequest decode(Object result) {
    result as List<Object?>;
    return ProgressRequest(
      progress: result[0] as int?,
      hasError: result[1] as bool?,
    );
  }
}

class NativeApi {
  /// Constructor for [NativeApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NativeApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = StandardMessageCodec();

  Future<void> startAsync() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.pigeon_example_package.NativeApi.startAsync', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

class _FlutterApiCodec extends StandardMessageCodec {
  const _FlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is ProgressRequest) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return ProgressRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FlutterApi {
  static const MessageCodec<Object?> codec = _FlutterApiCodec();

  Future<void> sendProgressAsync(ProgressRequest request);

  static void setup(FlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.pigeon_example_package.FlutterApi.sendProgressAsync', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.pigeon_example_package.FlutterApi.sendProgressAsync was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final ProgressRequest? arg_request = (args[0] as ProgressRequest?);
          assert(arg_request != null,
              'Argument for dev.flutter.pigeon.pigeon_example_package.FlutterApi.sendProgressAsync was null, expected non-null ProgressRequest.');
          await api.sendProgressAsync(arg_request!);
          return;
        });
      }
    }
  }
}
