version: '3'

services:
  wiki:
    image: requarks/wiki:2
    depends_on:
      - db
    container_name: wikijs
    environment:
      DB_TYPE: postgres
    ports:
      - 3000:3000
    volumes:
      - ./config/config.yml:/wiki/config.yml

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/postgresql/data