# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Demo
  # SVGKit does not work on Apple Silicon simulator (https://github.com/SVGKit/SVGKit/pull/717)
  # So we have to specify github url rather than https://cocoapods.org/
  pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'

end

# https://stackoverflow.com/questions/77139617/clang-error-sdk-does-not-contain-libarclite-at-the-path
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
    end
  end
end