FROM mcr.microsoft.com/dotnet/sdk:6.0-alpine-amd64 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY sources/Demo/*.csproj ./
RUN dotnet restore

# Copy everything else and build
COPY sources/Demo ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine-amd64
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "Demo.dll"]