/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "stdafx.h"
#include "Server_constants.h"



const ServerConstants g_Server_constants;

ServerConstants::ServerConstants() {
}