sources:
  sidercar_logs:
    type: docker_logs
    include_containers: ["demo-vector-sidecar-app1"]

transforms:
  clean_logs:
    type: remap
    inputs: ["sidercar_logs"]
    source: |
      del(.container_created_at)
      del(.container_id)
      del(.host)
      del(.image)
      del(.label)
      del(.source_type)
      del(.stream)

sinks:
  rustfs:
    type: file
    inputs: ["clean_logs"]
    path: /tmp/logs/%Y-%m-%d.log
    encoding:
      codec: json
      pretty: false