# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imageProc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imageProc.proto',
  package='imageProc',
  syntax='proto3',
  serialized_pb=_b('\n\x0fimageProc.proto\x12\timageProc\"S\n\x12\x45nhancementRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x03 \x01(\x05\x12\r\n\x05image\x18\x04 \x01(\x0c\"a\n\x10\x45nhancementReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\r\n\x05width\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x0f\n\x07\x63hannel\x18\x04 \x01(\x05\x12\r\n\x05image\x18\x05 \x01(\x0c\x32X\n\tImageProc\x12K\n\x0b\x45nhancement\x12\x1d.imageProc.EnhancementRequest\x1a\x1b.imageProc.EnhancementReply\"\x00\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ENHANCEMENTREQUEST = _descriptor.Descriptor(
  name='EnhancementRequest',
  full_name='imageProc.EnhancementRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='imageProc.EnhancementRequest.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='imageProc.EnhancementRequest.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='imageProc.EnhancementRequest.channel', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='imageProc.EnhancementRequest.image', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=113,
)


_ENHANCEMENTREPLY = _descriptor.Descriptor(
  name='EnhancementReply',
  full_name='imageProc.EnhancementReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='imageProc.EnhancementReply.result', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='width', full_name='imageProc.EnhancementReply.width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height', full_name='imageProc.EnhancementReply.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='channel', full_name='imageProc.EnhancementReply.channel', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='imageProc.EnhancementReply.image', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=212,
)

DESCRIPTOR.message_types_by_name['EnhancementRequest'] = _ENHANCEMENTREQUEST
DESCRIPTOR.message_types_by_name['EnhancementReply'] = _ENHANCEMENTREPLY

EnhancementRequest = _reflection.GeneratedProtocolMessageType('EnhancementRequest', (_message.Message,), dict(
  DESCRIPTOR = _ENHANCEMENTREQUEST,
  __module__ = 'imageProc_pb2'
  # @@protoc_insertion_point(class_scope:imageProc.EnhancementRequest)
  ))
_sym_db.RegisterMessage(EnhancementRequest)

EnhancementReply = _reflection.GeneratedProtocolMessageType('EnhancementReply', (_message.Message,), dict(
  DESCRIPTOR = _ENHANCEMENTREPLY,
  __module__ = 'imageProc_pb2'
  # @@protoc_insertion_point(class_scope:imageProc.EnhancementReply)
  ))
_sym_db.RegisterMessage(EnhancementReply)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class ImageProcStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Enhancement = channel.unary_unary(
          '/imageProc.ImageProc/Enhancement',
          request_serializer=EnhancementRequest.SerializeToString,
          response_deserializer=EnhancementReply.FromString,
          )


  class ImageProcServicer(object):

    def Enhancement(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_ImageProcServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Enhancement': grpc.unary_unary_rpc_method_handler(
            servicer.Enhancement,
            request_deserializer=EnhancementRequest.FromString,
            response_serializer=EnhancementReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'imageProc.ImageProc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaImageProcServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Enhancement(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaImageProcStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def Enhancement(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    Enhancement.future = None


  def beta_create_ImageProc_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('imageProc.ImageProc', 'Enhancement'): EnhancementRequest.FromString,
    }
    response_serializers = {
      ('imageProc.ImageProc', 'Enhancement'): EnhancementReply.SerializeToString,
    }
    method_implementations = {
      ('imageProc.ImageProc', 'Enhancement'): face_utilities.unary_unary_inline(servicer.Enhancement),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_ImageProc_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('imageProc.ImageProc', 'Enhancement'): EnhancementRequest.SerializeToString,
    }
    response_deserializers = {
      ('imageProc.ImageProc', 'Enhancement'): EnhancementReply.FromString,
    }
    cardinalities = {
      'Enhancement': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'imageProc.ImageProc', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
