services:
  app1:
    image: demo-vector-app
    container_name: demo-vector-app1
    command: /app/Demo
  app2:
    image: demo-vector-app
    container_name: demo-vector-app2
    command: /app/Demo
  vector:
    image: timberio/vector:0.55.0-alpine
    container_name: demo-vector-vector
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock

