apiVersion: v1
kind: Service
metadata:
  name: busybox-svc
  labels:
    app: busybox-svc
spec:
  ports:
  - protocol: TCP
    name: busybox-svc-port
    port: 1234
    targetPort: 5678
  selector:
    app: busybox