sources:
  sidercar_logs:
    type: docker_logs
    include_containers: ["demo-vector-sidecar-app1"]

transforms:
  clean_logs:
    type: remap
    inputs: ["sidercar_logs"]
    source: |
      del(.container_created_at)
      del(.container_id)
      del(.host)
      del(.image)
      del(.label)
      del(.source_type)
      del(.stream)

sinks:
  console:
    type: console
    inputs: ["clean_logs"]
    encoding:
      codec: json
      pretty: true