name: hello_world
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  functional_widget_annotation: ^0.10.0
  rxdart: '>=0.27.4'
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

builders:
  functional_widget: ^0.6.0