name: hello_world
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  functional_widget_annotation: ^0.5.0
  rxdart: 0.22.1+1
  flutter:
    sdk: flutter

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

builders:
  functional_widget: ^0.6.0