services:
  app1:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: demo-vector-app1
    command: /app/Demo
  vector:
    image: timberio/vector:0.55.0-alpine
    container_name: demo-vector-vector
    network_mode: host
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - VECTOR_LOG=error
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}