version: "3"
services:
  nginx:
    image: docker-sample-nginx
    container_name: docker-sample-nginx
    ports:
    - 443:443
    networks:
      - proxy
  aspnet:
    image: docker-sample-aspnet6
    container_name: docker-sample-aspnet6
    networks:
      - proxy

networks:
  proxy: