version: 1
root:
  level: DEBUG
  handlers: [console, file]
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: console
  file:
    class: logging.FileHandler
    filename: logs/application.log
    formatter: file
formatters:
  console:
    '()': 'colorlog.ColoredFormatter'
    format: "{log_color}{asctime} [{levelname:.4}] {message}"
    style: "{"
  file:
    format: "{asctime} [{levelname:.4}] {message}"
    style: "{"