version: '3.7'

services:
  localstack:
    image: localstack/localstack:1.3.1
    ports:
      - 4566:4566
      - 8000:8080
    volumes:
      # - ./docker/localstack:/docker-entrypoint-initaws.d
      - /var/run/docker.sock:/var/run/docker.sock
      - 'localstack-data:/tmp/localstack'
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
    environment:
      - SERVICES=s3,dynamodb,ses
      # https://docs.localstack.cloud/integrations/aws-cli/#setting-up-local-region-and-credentials-to-run-localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-1
      - PERSISTENCE=${PERSISTENCE-}
      - LOCALSTACK_API_KEY=${LOCALSTACK_API_KEY-}
      - DISABLE_CORS_CHECKS=1

volumes:
  localstack-data:
    driver: 'local'