// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: option.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Demo {

  /// <summary>Holder for reflection information generated from option.proto</summary>
  public static partial class OptionReflection {

    #region Descriptor
    /// <summary>File descriptor for option.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OptionReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxvcHRpb24ucHJvdG8SBWdyZWV0Kj4KCFRpbWVab25lEgsKB21vcm5pbmcQ",
            "ABINCglhZnRlcm5vb24QARILCgdldmVuaW5nEAISCQoFbmlnaHQQA0IHqgIE",
            "RGVtb2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Demo.TimeZone), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum TimeZone {
    [pbr::OriginalName("morning")] Morning = 0,
    [pbr::OriginalName("afternoon")] Afternoon = 1,
    [pbr::OriginalName("evening")] Evening = 2,
    [pbr::OriginalName("night")] Night = 3,
  }

  #endregion

}

#endregion Designer generated code
