// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: imageProc.proto
#region Designer generated code

using System;
using System.Threading;
using grpc = global::Grpc.Core;

namespace ImageProc {
  public static partial class ImageProc
  {
    static readonly string __ServiceName = "imageProc.ImageProc";

    static readonly grpc::Marshaller<global::ImageProc.EnhancementRequest> __Marshaller_EnhancementRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ImageProc.EnhancementRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ImageProc.EnhancementReply> __Marshaller_EnhancementReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ImageProc.EnhancementReply.Parser.ParseFrom);

    static readonly grpc::Method<global::ImageProc.EnhancementRequest, global::ImageProc.EnhancementReply> __Method_Enhancement = new grpc::Method<global::ImageProc.EnhancementRequest, global::ImageProc.EnhancementReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Enhancement",
        __Marshaller_EnhancementRequest,
        __Marshaller_EnhancementReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ImageProc.ImageProcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ImageProc</summary>
    public abstract partial class ImageProcBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ImageProc.EnhancementReply> Enhancement(global::ImageProc.EnhancementRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ImageProc</summary>
    public partial class ImageProcClient : grpc::ClientBase<ImageProcClient>
    {
      /// <summary>Creates a new client for ImageProc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public ImageProcClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ImageProc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public ImageProcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected ImageProcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected ImageProcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ImageProc.EnhancementReply Enhancement(global::ImageProc.EnhancementRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Enhancement(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ImageProc.EnhancementReply Enhancement(global::ImageProc.EnhancementRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Enhancement, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ImageProc.EnhancementReply> EnhancementAsync(global::ImageProc.EnhancementRequest request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return EnhancementAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ImageProc.EnhancementReply> EnhancementAsync(global::ImageProc.EnhancementRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Enhancement, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override ImageProcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ImageProcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(ImageProcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Enhancement, serviceImpl.Enhancement).Build();
    }

  }
}
#endregion
