version: '3'

services:
  wiki:
    image: requarks/wiki:2
    container_name: wikijs
    ports:
      - 3000:3000
    volumes:
      - ./wiki.js/data:/data
      - ./wiki.js/config/config.yml:/wiki/config.yml 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms400m -Xmx400m
      - ELASTIC_PASSWORD=password
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300